# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
