# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nome da Empresa')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan da Empresa')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Endereço')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Logo Marca')),
                ('about', models.TextField(blank=True, verbose_name='Sobre a Empresa')),
            ],
            options={
                'verbose_name_plural': 'Configurações',
                'verbose_name': 'Configuração',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Nome da RedeSocial')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Config')),
            ],
            options={
                'verbose_name_plural': 'Rede Sociais',
                'verbose_name': 'Rede Sociais',
            },
        ),
    ]
